---
apiVersion: v1
kind: Namespace
metadata:
  name: metallb
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: metallb
  namespace: metallb
spec:
  interval: 24h
  url: https://metallb.github.io/metallb
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: metallb
spec:
  interval: 30m
  chart:
    spec:
      chart: metallb
      version: 0.14.9
      reconcileStrategy: ChartVersion
      interval: 12h
      sourceRef:
        kind: HelmRepository
        name: metallb
        namespace: metallb
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
