---
apiVersion: v1
kind: Namespace
metadata:
  name: provisioners
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: nfs-provisioner
  namespace: provisioners
spec:
  interval: 24h
  url: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: nfs-provisioner
  namespace: provisioners
spec:
  interval: 30m
  chart:
    spec:
      chart: nfs-subdir-external-provisioner
      version: 4.0.18
      sourceRef:
        kind: HelmRepository
        name: nfs-provisioner
      interval: 12h
  values:
    # https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner/blob/nfs-subdir-external-provisioner-4.0.18/charts/nfs-subdir-external-provisioner/values.yaml
    replicaCount: 1
    strategyType: Recreate

    nfs:
      server: 192.168.10.4
      path: /mnt/pool0/kong
      mountOptions:
      - vers=3
      - nosuid

    storageClass:
      defaultClass: true
      provisionerName: nfs-provisioner
      name: nfs-storage
      reclaimPolicy: Delete
      archiveOnDelete: false
