apiVersion: v1
kind: Namespace
metadata:
  name: openebs
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: openebs
  namespace: openebs
spec:
  interval: 24h
  url: https://openebs.github.io/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: openebs
  namespace: openebs
spec:
  interval: 30m
  chart:
    spec:
      chart: openebs
      version: 3.10.0
      sourceRef:
        kind: HelmRepository
        name: openebs
        namespace: openebs
      interval: 12h
  values:
    ndm:
      enabled: false
    ndmOperator:
      enabled: false
