---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    pod-security.kubernetes.io/enforce: privileged
  name: csi-proxmox
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: proxmox-csi-plugin
  namespace: csi-proxmox
spec:
  type: oci
  interval: 60m0s
  url: oci://ghcr.io/sergelogvinov/charts/proxmox-csi-plugin
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: csi-proxmox
  namespace: csi-proxmox
spec:
  interval: 30m
  chart:
    spec:
      chart: csi-proxmox
      version: 0.2.1
      sourceRef:
        kind: HelmRepository
        name: proxmox-csi-plugin
        namespace: csi-proxmox
      interval: 12h
  values:
    config:
      clusters:
      - url: https://raphael.eth0.work:8006/api2/json
        insecure: false
        token_id: "kubernetes-csi@pve!csi"
        token_secret: "88e035c8-c963-4fee-9f1e-c1e77f22500b"
        region: boo

    node:
      kubeletDir: /var/lib/k0s/kubelet

    storageClass:
    - name: proxmox-data-xfs
      storage: local-lvm
      ssd: true
      reclaimPolicy: Delete
      fstype: xfs
    - name: proxmox-data
      storage: local-lvm
      ssd: true
      reclaimPolicy: Delete
      fstype: ext4
