apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: snapshot-controller
  namespace: kube-system
spec:
  type: oci
  interval: 60m0s
  url: oci://ghcr.io/democratic-csi/charts/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: snapshot-controller
  namespace: kube-system
spec:
  interval: 60m
  chart:
    spec:
      chart: snapshot-controller
      version: 0.3.0
      sourceRef:
        kind: HelmRepository
        name: snapshot-controller
        namespace: kube-system
      interval: 12h
