# helm upgrade --install --namespace velero --create-namespace velero vmware-tanzu/velero -f values.yaml --version 10.0.0
apiVersion: v1
kind: Namespace
metadata:
  name: velero
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: velero
  namespace: velero
spec:
  type: oci
  interval: 60m0s
  url: oci://ghcr.io/vmware-tanzu/charts/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: velero
  namespace: velero
spec:
  interval: 60m
  chart:
    spec:
      chart: velero
      version: 10.0.0
      sourceRef:
        kind: HelmRepository
        name: velero
        namespace: velero
      interval: 12h
  values:
    snapshotsEnabled: false

    initContainers:
      - name: velero-plugin-for-volume
        image: replicated/local-volume-provider:0.6.10
        volumeMounts:
        - mountPath: /target
          name: plugins

    configuration:
      backupStorageLocation:
      - name: default
        provider: replicated.com/nfs
        bucket: hostpathsnapshots
        config:
          server: 192.168.10.10
          path: /mnt/bebop/boo/velero

    configMaps:
      local-volume-provider-config:
        labels:
          velero.io/plugin-config: ""
          replicated.com/nfs: ObjectStore
          replicated.com/hostpath: ObjectStore
        data:
          securityContextRunAsUser: "1001"
          securityContextRunAsGroup: "1001"
          securityContextFsGroup: "1001"
