---
apiVersion: v1
kind: Namespace
metadata:
  name: haproxy-ingress
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: haproxy-ingress
  namespace: haproxy-ingress
spec:
  interval: 24h
  url: https://haproxytech.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: haproxy-ingress
  namespace: haproxy-ingress
spec:
  interval: 30m
  chart:
    spec:
      chart: kubernetes-ingress
      version: 1.32.4
      sourceRef:
        kind: HelmRepository
        name: haproxy-ingress
        namespace: haproxy-ingress
      interval: 12h
  values:
    installCRDs: true
