---
apiVersion: v1
kind: Namespace
metadata:
  name: haproxy-ingress
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: haproxy-ingress
  namespace: haproxy-ingress
spec:
  interval: 24h
  url: https://haproxytech.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: haproxy-ingress
  namespace: haproxy-ingress
spec:
  interval: 30m
  chart:
    spec:
      chart: kubernetes-ingress
      version: 1.32.4
      sourceRef:
        kind: HelmRepository
        name: haproxy-ingress
        namespace: haproxy-ingress
      interval: 12h
  values:
    controller:
      ingressClass: haproxy
      ingressClassResource:
        default: true
        name: haproxy
      extraArgs:
      - --disable-ipv6
      # - --configmap-tcp-services=haproxy-ingress/tcp-services
      # - --default-backend-service=haproxy-ingress/default-backend
      dnsPolicy: ClusterFirstWithHostNet
      config:
        scale-server-slots: "10"
        src-ip-header: X-Forwarded-For,1
        # ssl-certificate: "haproxy-ingress/boo-tls"
        # cr-global: haproxy-ingress/global
        # cr-defaults: haproxy-ingress/defaults
        frontend-config-snippet: |
          capture request header X-Forwarded-For len 32
          capture request header X-Forwarded-Proto len 32
      service:
        type: LoadBalancer
        loadBalancerIP: 192.168.10.70
        annotations:
          metallb.universe.tf/allow-shared-ip: "10.70"
      serviceMonitor:
        enabled: true
    defaultBackend:
      enabled: false
