apiVersion: v1
kind: Namespace
metadata:
  name: harbor
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: harbor
  namespace: harbor
spec:
  interval: 5m
  url: https://helm.goharbor.io
---
apiVersion: v1
kind: Secret
metadata:
  name: secret-key
  namespace: harbor
type: Opaque
data:
  secretKey: ENC[AES256_GCM,data:+8zOeih6JrSvi93mriXg6qEx9ywheinK,iv:Hj38gEssaXjB8N9f4ZRdB36VnRFBididdtp9c6KgFiM=,tag:mZfSZtJgCtAWKyNAHkP/7w==,type:str]
sops:
  age:
  - recipient: age1wpk6a50fj9hepmve43dtx36fr6rfat6nsms6fx6rf4x2udmmtutsmtzctr
    enc: |
      -----BEGIN AGE ENCRYPTED FILE-----
      YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3UVlUYyt6M29KRXZnUHBy
      WktUNmNBSXo4WUJ6ampnOGtHVzRUb04vL2lNCjJkMVJVczMyZUxxRWgrQ1U3OXBz
      T213ZHZhaFAvOThRVFZyYkpFTDk3NncKLS0tIFNPVkFYaVhqMEk4STNPUCtocDli
      WE9xQUlNK1B4RmowUjZLZlFtaVhOU00KRw9wA6ZIwfMclGiQJ8kTD5KcWDvPLF2D
      iGSgqSswxPoTm6ktpmZZgcxQYZBwkkeHjvt+LC690/7jxrc7wLak8A==
      -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-01-01T13:27:17Z"
  encrypted_regex: ^(data|stringData)$
  version: 3.8.1
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: harbor
  namespace: harbor
spec:
  chart:
    spec:
      chart: harbor
      version: 1.13.1
      sourceRef:
        kind: HelmRepository
        name: harbor
  interval: 50m
  install:
    remediation:
      retries: 3
  values:
    # https://raw.githubusercontent.com/goharbor/harbor-helm/v1.13.1/values.yaml
    expose:
      type: ingress
      tls:
        enabled: true
        certSource: secret
        secret:
          secretName: harbor-tls
          notarySecretName: notary-tls
      ingress:
        hosts:
          core: registry.boo.eth0.work
        controller: default
        className: haproxy
        annotations:
          ingress.kubernetes.io/ssl-redirect: "true"
        harbor:
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt

    externalURL: https://registry.boo.eth0.work

    internalTLS:
      enabled: false

    ipFamily:
      ipv6:
        enabled: false

    persistence:
      enabled: true
      resourcePolicy: "keep"
      persistentVolumeClaim:
        registry:
          storageClass: nfs-storage
        chartmuseum:
          storageClass: nfs-storage
        jobservice:
          storageClass: nfs-storage
        database:
          storageClass: nfs-storage
        redis:
          storageClass: nfs-storage
        trivy:
          storageClass: nfs-storage

    imagePullPolicy: IfNotPresent

    # Senha inicial. Alterar depois de instalar
    harborAdminPassword: "Harbor12345"

    existingSecretSecretKey: secret-key

    chartmuseum:
      enabled: false

    trivy:
      enabled: false

    notary:
      enabled: false
