apiVersion: v1
kind: Namespace
metadata:
  name: immich
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: immich
  namespace: immich
spec:
  type: oci
  interval: 60m0s
  url: oci://ghcr.io/immich-app/immich-charts/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: immich
  namespace: immich
spec:
  interval: 60m
  chart:
    spec:
      chart: immich
      version: 0.9.3
      sourceRef:
        kind: HelmRepository
        name: immich
        namespace: immich
      interval: 12h
  values:
    image:
      tag: v1.135.1

    immich:
      metrics:
        enabled: true
      persistence:
        library:
          existingClaim: immich-store

      # ref: https://immich.app/docs/install/config-file/
      configuration: {}

    server:
      env:
      - name: REDIS_HOSTNAME
        value: immich-redis-master
      - name: IMMICH_MACHINE_LEARNING_URL
        value: http://immich-machine-learning:3003
      - name: DB_HOSTNAME
        value: 192.168.10.10
      - name: DB_DATABASE_NAME
        value: immich
      - name: DB_USERNAME
        value: immich
      - name: IMMICH_TELEMETRY_INCLUDE # telemetria do prometheus
        value: all
      - name: DB_PASSWORD
        valueFrom:
          secretKeyRef:
            name: immich-env
            key: DB_PASSWORD
      ingress:
        main:
          enabled: true
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt
          hosts:
          - host: immich.boo.eth0.work
            paths:
            - path: /
          tls:
          - secretName: immich-le-cert
            hosts:
            - immich.boo.eth0.work

    machine-learning:
      persistence:
        cache:
          type: pvc
          storageClass: nfs-storage

    redis:
      enabled: true
      master:
        persistence:
          enabled: false
