apiVersion: v1
kind: Namespace
metadata:
  name: pihole
---
apiVersion: v1
kind: Secret
metadata:
  name: pihole-secret
  namespace: pihole
data:
  password: ENC[AES256_GCM,data:Rb3eSbGNg0D/5INF8pU6u0Wvcs7jALfw,iv:FK80ukaQuJTPLvn6ir+ZhuTjhWYa31XBMFmQA52alRk=,tag:oe7TvoV1St4ow69QNnTjkw==,type:str]
type: Opaque
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
  - recipient: age1wpk6a50fj9hepmve43dtx36fr6rfat6nsms6fx6rf4x2udmmtutsmtzctr
    enc: |
      -----BEGIN AGE ENCRYPTED FILE-----
      YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUcytnY3ZyZVp5cjNZNW1T
      UEN1WUUra2cvb0JnckFHWWFkdTFobDhOOVNBCkhWR0ZPTC9PYXU2Q1p2VUpBTUxK
      SmdMczEwOFN2V1FxZU1uQnhSd2hHM3MKLS0tIEhJYUtkb3d1UmV0VGdvV2xKZnY3
      SG4yMHNkS2d3L3R1Uy9NQlFZeXZKOTgKu0ATm6BYHwv/m8k+667/5iIGFSuKvGbX
      uwG/8bsnhFrz26KaVB1hvIgspf/LyQprQigoL0HuhGGS5rMBa3Bg/A==
      -----END AGE ENCRYPTED FILE-----
  lastmodified: "2023-12-25T22:32:07Z"
  mac: ENC[AES256_GCM,data:sJ1COrtSZzpw4g5Y9+SpD/+y5a2Pk1JKSdKITfmORQic2tiVXpA5TrbP6puuv7rgilQzJOJMVGx2x3wb4IXpygj0WaW2+t4iJufWSeP4xO6wS0faCwIYSb8R7Ndfu8W0bSzWJwo9si7bIHQL5J/5l7kyJa50WmyFxwsRDE3pg3M=,iv:pDb11NTg9jLM/4ONR+qwFGTTSBEGLmOS5swLcSDBb6A=,tag:m6d2G7bVe9zGvjxQV2XBcQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.8.1
---
apiVersion: v1
kind: Secret
metadata:
  name: pihole-secret
  namespace: pihole
data:
  password: cGhvZWxlcGFzc3dvcmQ=
type: Opaque
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: pihole
  namespace: pihole
spec:
  interval: 5m
  url: https://mojo2600.github.io/pihole-kubernetes/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: pihole
  namespace: pihole
spec:
  chart:
    spec:
      chart: pihole
      sourceRef:
        kind: HelmRepository
        name: pihole
  interval: 50m
  install:
    remediation:
      retries: 3
  values:
    serviceDns:
      mixedService: true
      type: LoadBalancer
      loadBalancerIP: 192.168.10.70
      annotations:
        metallb.universe.tf/allow-shared-ip: "10.70"
      externalTrafficPolicy: Cluster

    serviceDhcp:
      enabled: false

    virtualHost: pi.boo.eth0.work

    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
      hosts:
      - pi.boo.eth0.work
      tls:
      - secretName: pi-le-cert
        hosts:
        - pi.boo.eth0.work

    persistentVolumeClaim:
      enabled: true
      storageClass: nfs-storage

    admin:
      existingSecret: pihole-secret

    extraEnvVars:
      TZ: America/Sao_Paulo

    DNS1: "1.1.1.1"
    DNS2: "1.0.0.1"

    podDnsConfig:
      enabled: false

    dnsmasq:
      customSettings:
        minTTL: # nome dessa chave é livre
          min-cache-ttl=3600 # 1h é o valor máximo permitido pelo dnsmasq
