apiVersion: v1
kind: Namespace
metadata:
  name: plex
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: config
  namespace: plex
spec:
  storageClassName: freenas-iscsi-csi
  resources:
    requests:
      storage: 5G
  accessModes:
  - ReadWriteOnce
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media
  namespace: plex
spec:
  storageClassName: manual
  resources:
    requests:
      storage: 500G
  accessModes:
  - ReadWriteMany
  volumeName: plex-media
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-media
spec:
  capacity:
    storage: 500G
  nfs:
    server: 192.168.10.10
    path: /mnt/bebop/plex
  accessModes:
  - ReadWriteMany
  storageClassName: manual
  volumeMode: Filesystem
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: plex
  namespace: plex
spec:
  selector:
    matchLabels:
      eth0.work/service: plex
  serviceName: plex
  replicas: 1
  template:
    metadata:
      labels:
        eth0.work/service: plex
    spec:
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: config
      - name: media
        persistentVolumeClaim:
          claimName: media
      containers:
      - name: plex
        image: plexinc/pms-docker:1.41.7.9823-59f304c16
        ports:
        - containerPort: 32400
          name: plex
        env:
        - name: TZ
          value: America/Sao_Paulo
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: ADVERTISE_IP
          value: https://plex.boo.eth0.work
        - name: HOSTNAME
          value: plex.boo.eth0.work
        - name: ALLOWED_NETWORKS
          value: "192.168.10.0/24,192.168.30.0/24"
        - name: VERSION
          value: docker
        volumeMounts:
        - name: config
          mountPath: /config
        - name: media
          mountPath: /media
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: conf-d
  namespace: plex
data:
  default.conf: |
    upstream plex {
      server plex-0.plex:32400;
    }

    server {
      listen                     80;
      server_name                _;

      error_log                  /var/log/nginx/error.log error;

      location /healthcheck {
        default_type text/plain;
        return 200 'OK';
      }

      location / {
        proxy_pass               http://plex;
        proxy_redirect           off;
        proxy_buffering          off;
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy
  namespace: plex
  labels:
    app.kubernetes.io/name: proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      eth0.work/service: proxy
  template:
    metadata:
      labels:
        eth0.work/service: proxy
    spec:
      volumes:
      - name: conf-d
        configMap:
          name: conf-d
      containers:
      - name: nginx
        image: nginx:latest
        imagePullPolicy: Always
        env:
        - name: TZ
          value: America/Sao_Paulo
        livenessProbe:
          httpGet:
            path: /healthcheck
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /healthcheck
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        ports:
        - containerPort: 80
        volumeMounts:
        - name: conf-d
          mountPath: /etc/nginx/conf.d
---
apiVersion: v1
kind: Service
metadata:
  name: plex
  namespace: plex
  annotations:
    metallb.universe.tf/allow-shared-ip: plexserver
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.10.55
  selector:
    eth0.work/service: proxy
  ports:
  - name: plex
    protocol: TCP
    port: 32400
  - name: dlna
    protocol: TCP
    port: 32469
---
apiVersion: v1
kind: Service
metadata:
  name: plex-udp
  namespace: plex
  annotations:
    metallb.universe.tf/allow-shared-ip: plexserver
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.10.55
  selector:
    eth0.work/service: plex
  ports:
  - name: dlna-udp
    protocol: UDP
    port: 1900
  - name: discovery-udp
    port: 5353
    protocol: UDP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: plex
  namespace: plex
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  rules:
  - host: plex.boo.eth0.work
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: plex
            port:
              name: plex
  tls:
  - secretName: plex-le-cert
    hosts:
    - plex.boo.eth0.work
