apiVersion: v1
kind: Namespace
metadata:
  name: plex
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: config
  namespace: plex
spec:
  storageClassName: openebs-hostpath
  resources:
    requests:
      storage: 5G
  accessModes:
  - ReadWriteOnce
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media
  namespace: plex
spec:
  storageClassName: manual
  resources:
    requests:
      storage: 500G
  accessModes:
  - ReadWriteMany
  volumeName: plex-media
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-media
spec:
  capacity:
    storage: 500G
  nfs:
    server: 192.168.10.4
    path: /mnt/pool0/plex
  accessModes:
  - ReadWriteMany
  storageClassName: manual
  volumeMode: Filesystem
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: plex
  namespace: plex
spec:
  selector:
    matchLabels:
      eth0.work/service: plex
  serviceName: plex
  replicas: 1
  template:
    metadata:
      labels:
        eth0.work/service: plex
    spec:
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: config
      - name: media
        persistentVolumeClaim:
          claimName: media
      containers:
      - name: plex
        image: plexinc/pms-docker:1.32.8.7639-fb6452ebf
        ports:
        - containerPort: 32400
          name: plex
        env:
        - name: TZ
          value: America/Sao_Paulo
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: ADVERTISE_IP
          value: https://plex.boo.eth0.work
        - name: HOSTNAME
          value: plex.boo.eth0.work
        - name: ALLOWED_NETWORKS
          value: "192.168.10.0/24,192.168.30.0/24"
        - name: VERSION
          value: docker
        volumeMounts:
        - name: config
          mountPath: /config
        - name: media
          mountPath: /media
---
apiVersion: v1
kind: Service
metadata:
  name: plex
  namespace: plex
  annotations:
    metallb.universe.tf/allow-shared-ip: plexserver
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.10.55
  selector:
    eth0.work/service: plex
  ports:
  - name: plex
    protocol: TCP
    port: 32400
  - name: dlna
    protocol: TCP
    port: 32469
---
apiVersion: v1
kind: Service
metadata:
  name: plex-udp
  namespace: plex
  annotations:
    metallb.universe.tf/allow-shared-ip: plexserver
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.10.55
  selector:
    eth0.work/service: plex
  ports:
  - name: dlna-udp
    protocol: UDP
    port: 1900
  - name: discovery-udp
    port: 5353
    protocol: UDP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: plex
  namespace: plex
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  rules:
  - host: plex.boo.eth0.work
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: plex
            port:
              name: plex
  tls:
  - secretName: plex-le-cert
    hosts:
    - plex.boo.eth0.work
