---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: main-pool
  namespace: metallb
spec:
  addresses:
  - 192.168.10.50-192.168.10.59
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: dns-pool
  namespace: metallb
spec:
  addresses:
  - 192.168.10.60
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: main-l2-advertisement
  namespace: metallb
spec:
  ipAddressPools:
  - main-pool
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: dns-l2-advertisement
  namespace: metallb
spec:
  ipAddressPools:
  - dns-pool
  nodeSelectors:
  - matchLabels:
      kubernetes.io/hostname: boo-1
