---
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-apikey-secret
  namespace: cert-manager
data:
  apikey: YWJj
type: Opaque
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
  namespace: cert-manager
spec:
  acme:
    email: fabiano@nunes.me
    server: https://acme-v02.api.letsencrypt.org/directory
    preferredChain: "ISRG Root X1"
    privateKeySecretRef:
      name: letsencrypt-issuer-account-key
    solvers:
    - dns01:
        cloudflare:
          email: fabiano@nunes.me
          apiTokenSecretRef:
            name: cloudflare-apikey-secret
            key: apikey
      selector:
        dnsZones:
        - eth0.work
