---
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-apikey-secret
  namespace: cert-manager
data:
  apikey: ENC[AES256_GCM,data:KOkq3XFnbGoYp/udLKl3Q6e6+pQyaV3pak1iks3/bW3BD9lRxmQLytgr+j6TzEwxeazLYjiYgDA=,iv:o07Bjn6DzQuhPT1FMYcQv/ahGPyzDW/xDfOkE8Grczg=,tag:dUCuGn/re4AvQRfrJ1jVaQ==,type:str]
type: Opaque
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
  - recipient: age1wpk6a50fj9hepmve43dtx36fr6rfat6nsms6fx6rf4x2udmmtutsmtzctr
    enc: |
      -----BEGIN AGE ENCRYPTED FILE-----
      YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWQmI0bUp1SEFIZWdWTmpn
      dUdjaElWOGNmaXMzbkxQRStNR2syWWdZVkJnCjZoRVB0eTZEYnB6ZElYL1hseFNL
      L1JWMlowWWNMOFNNaFhxWDg1OFRJdHMKLS0tIEd5UmZadVp1M3RpTkttZ3E2b1V0
      NmJNcUlqeWpwVXFPYUhxb0lYM1o5MkEKhaA0s6RV1Oj07LjOEYd347W7QpZ70mpr
      SNDfXycRmge3stlLvHFqXNDpstOUVn8MD9QzW8dEchLKnfSk62dbkw==
      -----END AGE ENCRYPTED FILE-----
  lastmodified: "2023-12-25T21:53:15Z"
  mac: ENC[AES256_GCM,data:GuwXg7VwoqkH/CBPGs3qc/yYALMCNG9E6r6kXeLkAq381wqKtfsuXyV9mSbc8QfNM+ZpLsuURuXY9MXVGceLUD6PoDiKEhKwyo2ZcaRIlPdfM2O1DjqRgz3UPG2tenhdnfr6DcmixAS4O2IOA36CPZpKBwePVIIEDKBtV/scsoY=,iv:aad1xmiuf7zCgbs/oLUUfdMh6kuuMSOwj57HSj37Zu4=,tag:ZHJaHqNLoWkSLN5tjaUUyg==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.8.1
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
  namespace: cert-manager
spec:
  acme:
    email: fabiano@nunes.me
    server: https://acme-v02.api.letsencrypt.org/directory
    preferredChain: "ISRG Root X1"
    privateKeySecretRef:
      name: letsencrypt-issuer-account-key
    solvers:
    - dns01:
        cloudflare:
          email: fabiano@nunes.me
          apiTokenSecretRef:
            name: cloudflare-apikey-secret
            key: apikey
      selector:
        dnsZones:
        - eth0.work
