apiVersion: v1
kind: Service
metadata:
  name: bebop
  namespace: external-services
  labels:
    app: bebop
spec:
  clusterIP: None
  ports:
  - protocol: TCP
    name: metrics
    port: 80
---
apiVersion: v1
kind: Endpoints
metadata:
  name: bebop
  namespace: external-services
subsets:
- addresses:
  - ip: 192.168.10.10
  ports:
  - port: 9100
    name: metrics
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus-bebop
  namespace: external-services
  labels:
    jobLabel: truenas
spec:
  jobLabel: jobLabel
  endpoints:
  - honorLabels: true
    path: /metrics
    port: metrics
    scheme: http
    scrapeTimeout: 10s
  namespaceSelector:
    matchNames:
    - external-services
  selector:
    matchLabels:
      app: bebop
