apiVersion: ingress.v1.haproxy.org/v1
kind: Backend
metadata:
  name: firewall
  namespace: external-services
spec:
  config:
    mode: http
    balance:
      algorithm: "leastconn"
    abortonclose: disabled
    forwardfor:
      enabled: enabled
    default_server:
      ssl: enabled
      check: enabled
      verify: none
---
apiVersion: v1
kind: Service
metadata:
  name: firewall
  namespace: external-services
spec:
  clusterIP: None
  ports:
  - protocol: TCP
    name: https
    port: 443
---
apiVersion: v1
kind: Endpoints
metadata:
  name: firewall
  namespace: external-services
subsets:
- addresses:
  - ip: 192.168.10.1
  ports:
  - port: 443
    name: https
---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: firewall
  namespace: external-services
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    cr-backend: external-services/firewall
spec:
  ingressClassName: haproxy
  rules:
  - host: firewall.boo.eth0.work
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: firewall
            port:
              name: https
  tls:
  - secretName: firewall-tls
    hosts:
    - firewall.boo.eth0.work
