apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: external-services
resources:
- namespace.yaml
- proxmox.yaml
- truenas.yaml
- shredder.yaml
- raphael.yaml
- encefalite.yaml
- cachumba.yaml
