apiVersion: "core.haproxy.org/v1alpha2"
kind: Backend
metadata:
  name: truenas
  namespace: external-services
spec:
  config:
    mode: http
    balance:
      algorithm: "leastconn"
    abortonclose: disabled
    forwardfor:
      enabled: enabled
    default_server:
      ssl: enabled
      check: enabled
      verify: none
---
apiVersion: v1
kind: Service
metadata:
  name: truenas
  namespace: external-services
spec:
  clusterIP: None
  ports:
  - protocol: TCP
    name: https
    port: 443
---
apiVersion: v1
kind: Endpoints
metadata:
  name: truenas
  namespace: external-services
subsets:
- addresses:
  - ip: 192.168.10.4
  ports:
  - port: 443
    name: https
---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: truenas
  namespace: external-services
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    cr-backend: external-services/truenas
spec:
  ingressClassName: haproxy
  rules:
  - host: truenas.boo.eth0.work
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: truenas
            port:
              name: https
  tls:
  - secretName: truenas-tls
    hosts:
    - truenas.boo.eth0.work
